CBC_NORMALIZATION_DICT = {
    # Construction Types
    "type 1": "Type I",
    "type i": "Type I",
    "type 1a": "Type I-A",
    "1a": "Type I-A",
    "type ia": "Type I-A",
    "type 1b": "Type I-B",
    "1b": "Type I-B",
    "type ib": "Type I-B",
    "type 2": "Type II",
    "type ii": "Type II",
    "type 2a": "Type II-A",
    "2a": "Type II-A",
    "type iia": "Type II-A",
    "type 2b": "Type II-B",
    "type iib": "Type II-B",
    "type 3": "Type III",
    "type iii": "Type III",
    "type 3a": "Type III-A",
    "3a": "Type III-A",
    "type iiia": "Type III-A",
    "iiia": "Type III-A",
    "type 3b": "Type III-B",
    "3b": "Type III-B",
    "type iiib": "Type III-B",
    "iiib": "Type III-B",
    "type 4": "Type IV",
    "type iv": "Type IV",
    "mass timber": "Type IV",
    "heavy timber": "Type IV",
    "type 5": "Type V",
    "type v": "Type V",
    "type 5a": "Type V-A",
    "5a": "Type V-A",
    "type va": "Type V-A",
    "va": "Type V-A",
    "type 5b": "Type V-B",
    "5b": "Type V-B",
    "type vb": "Type V-B",
    "vb": "Type V-B",
    
    # --- Occupancy Classifications (with singular and plural forms) ---
    # Group I-2 (Healthcare)
    "hospital": "Group I-2",
    "hospitals": "Group I-2",
    "nursing home": "Group I-2",
    "nursing homes": "Group I-2",
    "assisted living": "Group I-2",
    "assisted living facility": "Group I-2",
    "assisted living facilities": "Group I-2",
    "memory care": "Group I-2",
    "memory care facility": "Group I-2",
    "memory care facilities": "Group I-2",
    "skilled nursing": "Group I-2",
    "skilled nursing facility": "Group I-2",
    "skilled nursing facilities": "Group I-2",
    "rehab hospital": "Group I-2",
    "rehab hospitals": "Group I-2",
    "rehabilitation hospital": "Group I-2",
    "rehabilitation hospitals": "Group I-2",
    "medical rehab": "Group I-2",
    "medical rehab facility": "Group I-2",
    "medical rehab facilities": "Group I-2",
    "medical facility": "Group I-2",
    "medical facilities": "Group I-2",
    "healthcare facility": "Group I-2",
    "healthcare facilities": "Group I-2",
    "health care facility": "Group I-2",
    "health care facilities": "Group I-2",
    
    # Group B (Business)
    "ambulatory care": "Group B",
    "ambulatory care facility": "Group B",
    "ambulatory care facilities": "Group B",
    "outpatient": "Group B",
    "outpatient care": "Group B",
    "outpatient facility": "Group B",
    "outpatient facilities": "Group B",
    "medical clinic": "Group B",
    "medical clinics": "Group B",
    "urgent care": "Group B",
    "urgent care center": "Group B",
    "urgent care centers": "Group B",
    "dialysis center": "Group B",
    "dialysis centers": "Group B",
    "office": "Group B",
    "offices": "Group B",
    "office space": "Group B",
    "office towers": "Group B",
    "business": "Group B",
    "businesses": "Group B",
    "clinic": "Group B",
    "clinics": "Group B",
    # "medical clinic": "Group B",
    # "medical clinics": "Group B",
    "professional service": "Group B",
    "professional services": "Group B",
    "bank": "Group B",
    "banks": "Group B",
    "post office": "Group B",
    "post offices": "Group B",
    "city hall": "Group B",
    "civic building": "Group B",
    "civic buildings": "Group B",
    
    # Group I-4 (Daycare)
    "child daycare": "Group I-4",
    "child daycare facility": "Group I-4",
    "child daycare facilities": "Group I-4",
    "infant care": "Group I-4",
    "infant care facility": "Group I-4",
    "infant care facilities": "Group I-4",
    "elder care": "Group I-4",
    "elder care facility": "Group I-4",
    "elder care facilities": "Group I-4",
    "adult day care": "Group I-4",
    "adult day care facility": "Group I-4",
    "adult day care facilities": "Group I-4",
    "daycare": "Group I-4",
    "daycares": "Group I-4",
    "daycare facility": "Group I-4",
    "daycare facilities": "Group I-4",
    "child care": "Group I-4",
    "child care center": "Group I-4",
    "child care centers": "Group I-4",
    "adult care": "Group I-4",
    "adult care center": "Group I-4",
    "adult care centers": "Group I-4",
    "preschool": "Group I-4",
    "preschools": "Group I-4",
    
    # Group I-3 (Detention)
    "prison": "Group I-3",
    "prisons": "Group I-3",
    "jail": "Group I-3",
    "jails": "Group I-3",
    "detention": "Group I-3",
    "detention center": "Group I-3",
    "detention centers": "Group I-3",
    "detention facility": "Group I-3",
    "detention facilities": "Group I-3",
    "correctional facility": "Group I-3",
    "correctional facilities": "Group I-3",
    "juvenile facility": "Group I-3",
    "juvenile facilities": "Group I-3",
    "juvenile detention": "Group I-3",
    "juvenile hall": "Group I-3",
    "reentry program": "Group I-3",
    "reentry programs": "Group I-3",
    
    # Group R (Residential - General)
    "residential": "Group R",
    "residence": "Group R",
    "residences": "Group R",
    "residential apartments": "Group R-2",
    "residential building": "Group R-2",
    "residential buildings": "Group R-2",
    "home": "Group R",
    "homes": "Group R",
    "living unit": "Group R",
    "living units": "Group R",
    "dwellings": "Group R",
    "dwelling unit": "Group R",
    "dwelling units": "Group R",
    "Group R residential": "Group R",
    
    # Group R-2 (Residential - Permanent, Multi-occupant)
    "apartment": "Group R-2",
    "apartments": "Group R-2",
    "apartment building": "Group R-2",
    "apartment buildings": "Group R-2",
    "condo": "Group R-2",
    "condo units": "Group R-2",
    "condos": "Group R-2",
    "condominium": "Group R-2",
    "condominiums": "Group R-2",
    "multi-family": "Group R-2",
    "multi family": "Group R-2",
    "multifamily": "Group R-2",
    "multi-unit": "Group R-2",
    "multi unit": "Group R-2",
    "multiunit": "Group R-2",
    "dorm": "Group R-2",
    "dorms": "Group R-2",
    "dormitory": "Group R-2",
    "dormitories": "Group R-2",
    "congregate living": "Group R-2",
    "congregate residence": "Group R-2",
    "congregate residences": "Group R-2",
    "transitional housing": "Group R-2",
    "assisted housing": "Group R-2",
    # "assisted living": "Group R-2",
    # "assisted living facility": "Group R-2",

    # Group R-2.1 (Personal care facilities)
    "personal care facility": "Group R-2.1",
    "personal care facilities": "Group R-2.1",
    "care facility": "Group R-2.1",
    "care facilities": "Group R-2.1",
    
    # Group R-1 (Residential - Transient)
    "hotel": "Group R-1",
    "hotels": "Group R-1",
    "motel": "Group R-1",
    "motels": "Group R-1",
    "transient housing": "Group R-1",
    "transient lodging": "Group R-1",
    "boarding house": "Group R-1",
    "boarding houses": "Group R-1",
    "bed and breakfast": "Group R-1",
    "bnb": "Group R-1",
    "short term rental": "Group R-1",
    "short-term rental": "Group R-1",
    "vacation rental": "Group R-1",
    "inn": "Group R-1",
    "inns": "Group R-1",
    "R-1 residential": "Group R-1",
    "R1 residential": "Group R-1",
    
    # Group R-3 (Residential - One and Two Family)
    "single-family": "Group R-3",
    "single family": "Group R-3",
    "single family home": "Group R-3",
    "single family homes": "Group R-3",
    "single family dwelling": "Group R-3",
    "single family dwellings": "Group R-3",
    "detached home": "Group R-3",
    "detached homes": "Group R-3",
    "townhouse": "Group R-3",
    "townhouses": "Group R-3",
    "town house": "Group R-3",
    "town houses": "Group R-3",
    "townhome": "Group R-3",
    "townhomes": "Group R-3",
    "duplex": "Group R-3",
    "duplexes": "Group R-3",
    "two-family": "Group R-3",
    "two family": "Group R-3",
    "two family dwelling": "Group R-3",
    "two family dwellings": "Group R-3",
    "group home": "Group R-3",
    "group homes": "Group R-3",
    "tiny home": "Group R-3",
    "tiny homes": "Group R-3",
    "tiny house": "Group R-3",
    "tiny houses": "Group R-3",
    "mobile home": "Group R-3",
    "mobile homes": "Group R-3",
    "manufactured home": "Group R-3",
    "manufactured homes": "Group R-3",
    "adu": "Group R-3",
    "adus": "Group R-3",
    "accessory dwelling unit": "Group R-3",
    "accessory dwelling units": "Group R-3",
    "r-3 residential": "Group R-3",
    "r3 residential": "Group R-3",
    
    # Group R-3.1 (California-specific - Licensed Care in R-3)
    "licensed care home": "Group R-3.1",
    "licensed care homes": "Group R-3.1",
    "residential care facility": "Group R-3.1",
    "residential care facilities": "Group R-3.1",
    "residential hospice": "Group R-3.1",
    "residential hospices": "Group R-3.1",
    "mobility unit": "Group R-3.1",
    "mobility units": "Group R-3.1",
    "medical housing unit": "Group R-3.1",
    "medical housing units": "Group R-3.1",
    "adult residential facility": "Group R-3.1",
    "adult residential facilities": "Group R-3.1",
    "small care home": "Group R-3.1",
    "small care homes": "Group R-3.1",
    "hospice house": "Group R-3.1",
    "hospice houses": "Group R-3.1",
    # "care facility": "Group R-3.1",
    # "care facilities": "Group R-3.1",
    "R-3.1 facility": "Group R-3.1",
    "R3.1 facility": "Group R-3.1",
    
    # Group E (Educational)
    "school": "Group E",
    "schools": "Group E",
    "university": "Group E",
    "universities": "Group E",
    "college": "Group E",
    "colleges": "Group E",
    "k-12": "Group E",
    "K12": "Group E",
    "elementary school": "Group E",
    "elementary schools": "Group E",
    "primary school": "Group E",
    "primary schools": "Group E",
    "middle school": "Group E",
    "middle schools": "Group E",
    "high school": "Group E",
    "high schools": "Group E",
    "kindergarten": "Group E",
    "kindergartens": "Group E",
    "classroom": "Group E",
    "classrooms": "Group E",
    "education": "Group E",
    "educational facility": "Group E",
    "educational facilities": "Group E",
    
    # Group A-1 (Assembly - Fixed Seating)
    "auditorium": "Group A-1",
    "auditoriums": "Group A-1",
    "theater": "Group A-1",
    "theaters": "Group A-1",
    "movie theater": "Group A-1",
    "movie theaters": "Group A-1",
    "cinema": "Group A-1",
    "cinemas": "Group A-1",
    "performing arts": "Group A-1",
    "performing arts center": "Group A-1",
    "performing arts centers": "Group A-1",
    "lecture hall": "Group A-1",
    "lecture halls": "Group A-1",
    
    # Group A-2 (Assembly - Food and Drink)
    "restaurant": "Group A-2",
    "restaurants": "Group A-2",
    "cafeteria": "Group A-2",
    "cafeterias": "Group A-2",
    "bar": "Group A-2",
    "bars": "Group A-2",
    "nightclub": "Group A-2",
    "nightclubs": "Group A-2",
    "night club": "Group A-2",
    "night clubs": "Group A-2",
    "food court": "Group A-2",
    "food courts": "Group A-2",
    "banquet hall": "Group A-2",
    "banquet halls": "Group A-2",
    "dining": "Group A-2",
    "dining facility": "Group A-2",
    "dining facilities": "Group A-2",
    "café": "Group A-2",
    "cafes": "Group A-2",
    "cafe": "Group A-2",
    "tavern": "Group A-2",
    "taverns": "Group A-2",
    
    # Group A-3 (Assembly - Worship, Recreation)
    "gym": "Group A-3",
    "gyms": "Group A-3",
    "gymnasium": "Group A-3",
    "gymnasiums": "Group A-3",
    "community hall": "Group A-3",
    "community halls": "Group A-3",
    "community center": "Group A-3",
    "community centers": "Group A-3",
    "church": "Group A-3",
    "churches": "Group A-3",
    "mosque": "Group A-3",
    "mosques": "Group A-3",
    "synagogue": "Group A-3",
    "synagogues": "Group A-3",
    "temple": "Group A-3",
    "temples": "Group A-3",
    "place of worship": "Group A-3",
    "places of worship": "Group A-3",
    "religious building": "Group A-3",
    "religious buildings": "Group A-3",
    "conference center": "Group A-3",
    "conference centers": "Group A-3",
    "convention center": "Group A-3",
    "convention centers": "Group A-3",
    "museum": "Group A-3",
    "museums": "Group A-3",
    "art gallery": "Group A-3",
    "art galleries": "Group A-3",
    "library": "Group A-3",
    "libraries": "Group A-3",
    "courtroom": "Group A-3",
    "courtrooms": "Group A-3",
    
    # Group A-4 (Assembly - Indoor Sports)
    "stadium": "Group A-4",
    "stadiums": "Group A-4",
    "arena": "Group A-4",
    "arenas": "Group A-4",
    "indoor stadium": "Group A-4",
    "indoor stadiums": "Group A-4",
    "tennis court": "Group A-4",
    "tennis courts": "Group A-4",
    "basketball court": "Group A-4",
    "basketball courts": "Group A-4",
    "volleyball court": "Group A-4",
    "volleyball courts": "Group A-4",
    "grandstand": "Group A-4",
    "grandstands": "Group A-4",
    "bleacher": "Group A-4",
    "bleachers": "Group A-4",
    
    # Group A-5 (Assembly - Outdoor Sports)
    "indoor pool": "Group A-5",
    "indoor pools": "Group A-5",
    "swimming pool": "Group A-5",
    "swimming pools": "Group A-5",
    "outdoor stadium": "Group A-5",
    "outdoor stadiums": "Group A-5",
    "amusement park": "Group A-5",
    "amusement parks": "Group A-5",
    "outdoor venue": "Group A-5",
    "outdoor venues": "Group A-5",
    "outdoor arena": "Group A-5",
    "outdoor arenas": "Group A-5",
    "fairground": "Group A-5",
    "fairgrounds": "Group A-5",
    
    # Group M (Mercantile)
    "retail": "Group M",
    "retail store": "Group M",
    "retail stores": "Group M",
    "store": "Group M",
    "stores": "Group M",
    "shop": "Group M",
    "shops": "Group M",
    "supermarket": "Group M",
    "supermarkets": "Group M",
    "grocery store": "Group M",
    "grocery stores": "Group M",
    "market": "Group M",
    "markets": "Group M",
    "department store": "Group M",
    "department stores": "Group M",
    "mall": "Group M",
    "malls": "Group M",
    "shopping center": "Group M",
    "shopping centers": "Group M",
    
    # Group S-1 (Storage - Moderate Hazard)
    "warehouse": "Group S-1",
    "warehouses": "Group S-1",
    "storage facility": "Group S-1",
    "storage facilities": "Group S-1",
    "self-storage": "Group S-1",
    "self storage": "Group S-1",
    "mini storage": "Group S-1",
    "furniture store": "Group S-1",
    "furniture stores": "Group S-1",
    
    # Group S-2 (Storage - Low Hazard)
    "parking garage": "Group S-2",
    "parking garages": "Group S-2",
    "parking structure": "Group S-2",
    "parking structures": "Group S-2",
    "parking deck": "Group S-2",
    "parking decks": "Group S-2",
    "cold storage": "Group S-2",
    "cold storage facility": "Group S-2",
    "cold storage facilities": "Group S-2",
    "refrigerated warehouse": "Group S-2",
    "refrigerated warehouses": "Group S-2",
    
    # Group F-1 (Factory - Moderate Hazard)
    "factory": "Group F-1",
    "factories": "Group F-1",
    "manufacturing": "Group F-1",
    "manufacturing facility": "Group F-1",
    "manufacturing facilities": "Group F-1",
    "industrial": "Group F-1",
    "industrial building": "Group F-1",
    "industrial buildings": "Group F-1",
    "bakery": "Group F-1",
    "bakeries": "Group F-1",
    "dry cleaning": "Group F-1",
    "dry cleaner": "Group F-1",
    "dry cleaners": "Group F-1",
    "laundry": "Group F-1",
    "laundries": "Group F-1",
    "textile mill": "Group F-1",
    "textile mills": "Group F-1",
    
    # Group F-2 (Factory - Low Hazard)
    "food processing": "Group F-2",
    "food processing facility": "Group F-2",
    "food processing facilities": "Group F-2",
    
    # Group U (Utility)
    "utility": "Group U",
    "utilities": "Group U",
    "utility building": "Group U",
    "utility buildings": "Group U",
    "shed": "Group U",
    "sheds": "Group U",
    "garage": "Group U",
    "garages": "Group U",
    "carport": "Group U",
    "carports": "Group U",
    "barn": "Group U",
    "barns": "Group U",
    "agricultural building": "Group U",
    "agricultural buildings": "Group U",
    "greenhouse": "Group U",
    "greenhouses": "Group U",
    "tank": "Group U",
    "tanks": "Group U",
    
    # CBC Specific Terms
    "egress": "egress",
    "exit": "exit",
    "exits": "exits",
    "fire rating": "fire rating",
    "fire-rating": "fire rating",
    "fire rated": "fire rated",
    "fire-rated": "fire rated",
    "fire resistance": "fire resistance",
    "fire-resistance": "fire resistance",
    "fire resistant": "fire resistant",
    "fire-resistant": "fire resistant",
    "hour rating": "hour rating",
    "hour-rating": "hour rating",
    "smoke detector": "smoke detector",
    "smoke detectors": "smoke detectors",
    "sprinkler": "sprinkler system",
    "sprinklers": "sprinkler system",
    "sprinkler system": "sprinkler system",
    "sprinkler systems": "sprinkler system",
    "fire alarm": "fire alarm system",
    "fire alarms": "fire alarm system",
    "fire alarm system": "fire alarm system",
    "fire alarm systems": "fire alarm system",
    "accessibility": "accessibility",
    "ada": "accessibility",
    "accessible": "accessible",
    "means of egress": "means of egress",
    "emergency exit": "emergency exit",
    "emergency exits": "emergency exits",
    "occupant load": "occupant load",
    "occupancy load": "occupant load",
    "occupancy limit": "occupant load",
    "floor area": "floor area",
    "egress width": "egress width",
    "exit width": "exit width",
    "travel distance": "travel distance",
    "dead end": "dead end",
    "dead-end": "dead end",
    "corridor": "corridor",
    "corridors": "corridors",
    "hallway": "corridor",
    "hallways": "corridors",
    "stair": "stairway",
    "stairs": "stairway",
    "stairway": "stairway",
    "stairways": "stairways",
    "handrail": "handrail",
    "handrails": "handrails",
    "guardrail": "guardrail",
    "guardrails": "guardrails",
    "guard rail": "guardrail",
    "guard rails": "guardrails",
    "railing": "railing",
    "railings": "railings",
    "ramp": "ramp",
    "ramps": "ramps",
    "door": "door",
    "doors": "doors",
    "ceiling height": "ceiling height",
    "ceiling heights": "ceiling height",
    "balcony": "balcony",
    "balconies": "balconies",
    "deck": "deck",
    "decks": "decks",
    "patio": "patio",
    "patios": "patios",
    "window": "window",
    "windows": "windows",
    "skylight": "skylight",
    "skylights": "skylights",
    "minimum dimension": "minimum dimension",
    "minimum dimensions": "minimum dimensions"
}